### ISSUE TITLE
List to dos / differences / incompatibilities to re:data

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#31]
It turned out that the Open Event JSON was implemented differently in some parts. Please list in a table what differences exist, the reason for the difference and what can still be implemented in the Open Event JSON

------------------------------------------------------------------------------------------------------------------------
So I am gonna jot down which fields in the API we need to change to become comaptible with re:data

Check out the re:data api (https://github.com/opendatacity/re-data/blob/master/doc/api.md) for reference. 

**/events**
* [x] start_time -> begin
* [x] end_time -> end

**/events/eventid/sessions**
* [x] start_time -> begin
* [x] end_time -> end
* [ ] Sessions api -> speakers [id, name]
* [ ] Sessions api -> tracks [id, label_de, label_en, color
* [x] Sessions api  -> level [ id, label_de, label_en]
* [x] Sessions api  -> lang [ id, label_de, label_en]
 
**/events/eventid/speakers**
 * [ ] linkedin,github,twitter... etc -> links [ ]

*implement the following*

* [ ] **`/events/<event-id>/days`**
* [x] **`/events/<event-id>/formats`**
* [x] **`/events/<event-id>/levels`**

**Comment by championswimmer** [comment]
So I am gonna jot down which fields in the API we need to change to become comaptible with re:data

**GET /events**
* [ ] start_time -> begin
* [ ] end_time -> end

**Comment by championswimmer** [comment]
@rafalkowalski @mananwason 
We need to do these changes synchronously across all the three projects. 

I'd suggest, first Rafal does it (pull request, not merge), then we see the generated json from the API, and we make same changes on webapp and Android, then we merge all three pull requests together.

**Comment by rafalkowalski** [comment]
ok

**Comment by mananwason** [comment]
@championswimmer Just one thought. Why are we trying to make it compatible to re:data unless there is some major benefit?

**Comment by rafalkowalski** [comment]
@championswimmer @mananwason @mariobehling Why do we need this changes?

**Comment by rafalkowalski** [comment]
https://github.com/fossasia/open-event-orga-server/pull/110

**Comment by mariobehling** [comment]
@rafalkowalski It seems like you do not understand the idea from of the modular approach, that we discussed at the beginning of the project. We want to be able to deploy data from any system that supports the redata format. Even if there is another system e.g. a Drupal system, that offers a redata file, we could still generate an app with this data.

@championswimmer @mananwason Could you tell me, how do you get the data from the server? Can you confirm that it is possible to use any dataset in the redata format and generate an app with standard color etc. using the format?

**Comment by rafalkowalski** [comment]
@mariobehling thanks for your answer ;) now it's clear for me

**Comment by mananwason** [comment]
@rafalkowalski Please see the update here

**Comment by rafalkowalski** [comment]
@championswimmer  @mananwason take a look https://github.com/opendatacity/re-data/blob/master/doc/api.md#sessions

**Comment by championswimmer** [comment]
@rafalkowalski I think we'll have to make 2 new tables in db `levels` and `formats` for each session.

**Comment by rafalkowalski** [comment]
@championswimmer on Re:data it's per event. I implemented it :)

**Comment by championswimmer** [comment]
Sorry I meant each event only. My bad :)

**Comment by mananwason** [comment]
@rafalkowalski @championswimmer Any other changes to be made apart from the ones listed here?

**Comment by mananwason** [comment]
Also check out the api I have setup here https://github.com/fossasia/open-event/tree/master/testapi/event/1 and point out any visible flaws.

**Comment by mariobehling** [comment]
Currently, the social media data and URLs are still missing from the web app for example. What is the implementation here? Does redata need to be changed?

**Comment by championswimmer** [comment]
We have separate fields and re:Data has an array. 

@rafalkowalski we have to change this as well

**Comment by mananwason** [comment]
@rafalkowalski Please see the updated differences for sessions api. We need to have arrays for ```tracks``` , ```  level ``` and ``` language ```

**Comment by rafalkowalski** [comment]
I saw it, Today i will implement it. @mananwason @championswimmer

**Comment by mananwason** [comment]
:+1:

**Comment by mananwason** [comment]
:+1:  Please notify once done
